### ISSUE TITLE
A "third heuristic" for unofficial APIs

### ISSUE THREAD

**Issue by thohan88** [hadley/web-scraping#1]
Great to see some examples from httr2, really appreciate the updates! 

Thought I would share my go-to method to identify "unofficial APIs": Searching in the network pane for a unique string you observe or suspect will be in the dataset

![image](https://github.com/hadley/web-scraping/assets/16469189/ddef0142-f407-47a9-871e-04602f3be096)

Thanks for all the great work!

**Comment by hadley** [comment]
Oooh great idea!
